In [3]:
pip install numpy


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
arr = np.random.randint(1,50, size = (10))
arr
arr

array([12, 47,  4, 38, 30, 39, 20, 18, 29, 33], dtype=int32)

In [7]:
np.mean(arr)

np.float64(27.0)

In [11]:
arr2 = np.random.randint(1,100, size = (2,5))
arr2

array([[16, 32,  7, 28, 20],
       [24, 96, 87, 96, 96]], dtype=int32)

In [12]:
np.size(arr)

10

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 909.4 kB/s eta 0:00:14
   -- ------------------------------------- 0.8/12.6 MB 997.2 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/12.6 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.6 MB 1.1 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/12.6 MB 1.0 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/12.6 MB 1.0 MB/s eta 0:00:11
   ----- ---------------------------------- 1.8/12.6 MB 1.0 MB/s eta 0:00:11
   ------ --------------------------------- 2.1/12.6 MB 959.6 kB/s eta 0:00:11
   ------ --------------------------------- 2.1/12.6 MB 959.6 kB/s eta 0:00:11
   ------- -------------------------------- 2.4/12.6 MB 962.5 kB/s eta 0:00:11
   -------


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
a = np.array([5,8,7])
b = np.array([7,8,9])
ab = np.add(a,b)
ab

array([12, 16, 16])

In [7]:
np.mean(ab)

np.float64(14.666666666666666)

In [ ]:
arr = np.random.randint(1,50, size = (10))